# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys,pymysql
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox, QWidget
import library
from Userbean import Userbean


class Ui_Form(QWidget):
    def __init__(self):
        QWidget.__init__(self)
        self.setupUi(self)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(231, 131)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(21)
        Form.setFont(font)
        self.pushButton_login = QtWidgets.QPushButton(Form)
        self.pushButton_login.setGeometry(QtCore.QRect(80, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_login.clicked.connect(self.login)
        self.lineEdit_username = QtWidgets.QLineEdit(Form)
        self.lineEdit_username.setGeometry(QtCore.QRect(50, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(50, 50, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_login.setText(_translate("Form", "登录"))
        self.lineEdit_username.setPlaceholderText(_translate("Form", "在此处输入用户名"))
        self.lineEdit_password.setPlaceholderText(_translate("Form", "在此处输入密码"))

    def login(self):
        db = pymysql.connect("localhost", "root", "db120325", "test")
        username = self.lineEdit_username.text()
        password = self.lineEdit_password.text()
        sql = "select password from secuser where uname=\'" + username + "\'"
        cursor = db.cursor()
        cursor.execute(sql)
        data = cursor.fetchone()
        if password == data[0]:
            self.window2=library.Ui_MainWindow(username)
            self.window2.show()
            self.close()
        else:
            QMessageBox.warning(self, "错误", "请检查输入的用户名和密码")

if __name__ == '__main__':
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())